using System;

namespace AutoDeepClone.Core;

internal class Consts
{
    public const string GenerateDeepCloneAttribute = @"
// <auto-generated/>
namespace AutoDeepClone.Core
{
    using System;

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    internal class DeepCloneAttribute : Attribute
    {
    }
}
";
}